before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: LJnNzAO92CKt/EcDtTOp09HyuKK5OzQdvZq+stOjkn6BHke7OnX0ZxCHLWDfbST2nFW2Eq4wsaV5p4y7fNGrsqWrTb9qqbmK7tTS1nztXebHc/tob9entUiflzTnPW6TcQwzOnGc2aw22Ifs+JezND12BUGl7VyLiZTL7lL0fw/ciApTqX/v0l1huHId7Phlf9CVHB6BhQy5eZ14IBpEgiAjaiVR4ZB8z9f4KsnpBnJRhMrILDHPPlaeYZENrvwdckLWgggc84Jw3/mIxd7ZXMfTAAxxfPpOq1GNk/3xyRXpcqn3XIW8hsVFEgdmuDYtguFLygzI/dPF5TVDxLwFGkdBXfABiLuF0Rb4nEmI7enblgJrAvcsu9IIlCPJLZlfcWUCKf7/5frSLfMj+sey+CFlQFrPne0eocOLNc5V5DIVQEf7eBSr277imDe+/TeXvPo+AQbQorLURQlEDRj4PLn5/92Ayg4XbatHB2x8uoPoZQH6p3h9CPD3My6ZVK6SDRfNheXQIbzFLiMLUAqiu6tjNwuJwQ0wiEvx67GMwEZBj9YHF6dlM/Hfw5kyPwmWWKTkS5kQVaAvMb6zrXOjM0+82mmr+eUFsD3yH/uiFt2pFDCwANc3K/gh/QzLSSb8G/FqioxXnUHVjnpqrQCjmnMuBioCh5R7ijmtC37xV20= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
